# pwr-menu config file
# shutdown Icon
shutdownIcon: "fa6s.power-off"
# reboot Icon
rebootIcon: "fa6s.repeat"
# logoff Icon
logoffIcon: "ri.logout-box-r-fill"
# Icon size
iconSizeW: 120 # width
iconSizeH: 120 # height
# Icon colors
iconColor: "#19e6c0"
iconColorActive: "black"
# Commands
shutdownCommand: "poweroff"
rebootCommand: "reboot"
logoffCommand: "hyprctl dispatch exit"
# Main window
MainWindow:
  backgrounColor: "#111122"
