[project]
name            = "pwrmenu"
version         = "0.1.2"
description     = "Modern PowerMenu"
readme          = "README.md"
requires-python = ">=3.12"
dependencies    = [
    "pyqt6>=6.9.0",
    "pyqtdarktheme>=2.1.0",
    "qtawesome>=1.4.0",
]
