[project]
name            = "pwrmenu"
version         = "0.0.0"
description     = "Modern PowerMenu"
readme          = "README.md"
requires-python = ">=3.12"
dependencies    = ["confz>=2.1.0", "pyqt6>=6.9.0", "qtawesome>=1.4.0"]
