[project]
name            = "pwrmenu"
version         = "0.1.2"
description     = "Modern PowerMenu"
readme          = "README.md"
requires-python = ">=3.12"
dependencies    = [
    "dbus-notification>=2024.7.2",
    "flet[all]>=0.27.3",
]
