# This file is used to configure the hyprpwmenu
# It is a YAML file, so make sure to follow the syntax rules
# You can use comments in YAML files by starting a line with '#'

buttons:
  - icon_path: "/home/antrax/.config/hyprpwmenu/shutdown.png"
    id: "buttonPowerOff"
    hint: "Power Off"
    command: "poweroff"

  - icon_path: "/home/antrax/.config/hyprpwmenu/reboot.png"
    id: "buttonRestart"
    hint: "Restart"
    command: "reboot"

  - icon_path: "/home/antrax/.config/hyprpwmenu/logoff.png"
    id: "buttonLogout"
    hint: "Log Off"
    command: "hyprctl dispatch exit"
