# This file is used to configure the hyprpwmenu
# It is a YAML file, so make sure to follow the syntax rules
# You can use comments in YAML files by starting a line with '#'

mainwindow:
  width: 500
  height: 150
