# This file is used to configure the hyprpwmenu
# It is a YAML file, so make sure to follow the syntax rules
# You can use comments in YAML files by starting a line with '#'

buttons:
  - icon: "A"
    id: "buttonPowerOff"
    command: "poweroff"

  - icon: "B"
    id: "buttonRestart"
    command: "reboot"

  - icon: "C"
    id: "buttonLogout"
    command: "hyprctl dispatch exit"
