# This file is used to configure the hyprpwmenu
# It is a YAML file, so make sure to follow the syntax rules
# You can use comments in YAML files by starting a line with '#'

# Main Window configuration
main_window:
  icon_size: 80 # size of the icons
  font_size: 18px; # Font size for the text under the buttons
  fullscreen: true # Set to true to make the main window fullscreen
  width: 720 # Width of the main window
  height: 350 # Height of the main window
  space_between_buttons: 60 # Space between buttons
  background_color: "#000000" # Background color of the main window

# Shutdown icon and command
shutdown:
  icon: "fa6s.power-off" # Path to the shutdown icon
  icon_color: "#9575CD" # Color of the icons
  icon_color_active: "black" # Color of the active icons
  command: "poweroff" # Command to execute when the shutdown icon is clicked

# Reboot icon and command
reboot:
  icon: "fa6s.repeat" # Path to the reboot icon
  icon_color: "#18FFFF" # Color of the icons
  icon_color_active: "black" # Color of the active icons
  command: "reboot" # Command to execute when the reboot icon is clicked

# Logoff icon and command
logoff:
  icon: "ri.logout-box-r-fill" # Path to the logoff icon
  icon_color: "#69F0AE" # Color of the icons
  icon_color_active: "black" # Color of the active icons
  command: "hyprctl dispatch exit" # Command to execute when the logout icon is clicked
