# This file is used to configure the hyprpwmenu
# It is a YAML file, so make sure to follow the syntax rules
# You can use comments in YAML files by starting a line with '#'

# Main Window configuration
main_window:
  fullscreen: true # Set to true to make the main window fullscreen
  width: 720 # Width of the main window
  height: 350 # Height of the main window
  space_between_buttons: 60 # Space between buttons

# Shutdown icon and command
shutdown:
  icon: "fa6s.power-off" # Path to the shutdown icon
  command: "poweroff" # Command to execute when the shutdown icon is clicked

# Reboot icon and command
reboot:
  icon: "fa6s.repeat" # Path to the reboot icon
  command: "reboot" # Command to execute when the reboot icon is clicked

# Logoff icon and command
logoff:
  icon: "ri.logout-box-r-fill" # Path to the logoff icon
  command: "hyprctl dispatch exit" # Command to execute when the logout icon is clicked
